# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCommander.ui'
#
# Created: Fri May 27 11:05:39 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RCommanderWindow(object):
    def setupUi(self, RCommanderWindow):
        RCommanderWindow.setObjectName("RCommanderWindow")
        RCommanderWindow.resize(786, 651)
        self.centralwidget = QtGui.QWidget(RCommanderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools_box = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_box.sizePolicy().hasHeightForWidth())
        self.tools_box.setSizePolicy(sizePolicy)
        self.tools_box.setObjectName("tools_box")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tuck_button = QtGui.QToolButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuck_button.sizePolicy().hasHeightForWidth())
        self.tuck_button.setSizePolicy(sizePolicy)
        self.tuck_button.setAutoRaise(True)
        self.tuck_button.setObjectName("tuck_button")
        self.horizontalLayout_2.addWidget(self.tuck_button)
        self.navigate_button = QtGui.QToolButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigate_button.sizePolicy().hasHeightForWidth())
        self.navigate_button.setSizePolicy(sizePolicy)
        self.navigate_button.setAutoRaise(True)
        self.navigate_button.setObjectName("navigate_button")
        self.horizontalLayout_2.addWidget(self.navigate_button)
        self.tools_box.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aseg_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aseg_button.sizePolicy().hasHeightForWidth())
        self.aseg_button.setSizePolicy(sizePolicy)
        self.aseg_button.setAutoRaise(True)
        self.aseg_button.setObjectName("aseg_button")
        self.horizontalLayout_3.addWidget(self.aseg_button)
        self.oselect_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oselect_button.sizePolicy().hasHeightForWidth())
        self.oselect_button.setSizePolicy(sizePolicy)
        self.oselect_button.setAutoRaise(True)
        self.oselect_button.setObjectName("oselect_button")
        self.horizontalLayout_3.addWidget(self.oselect_button)
        self.lclick_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lclick_button.sizePolicy().hasHeightForWidth())
        self.lclick_button.setSizePolicy(sizePolicy)
        self.lclick_button.setAutoRaise(True)
        self.lclick_button.setObjectName("lclick_button")
        self.horizontalLayout_3.addWidget(self.lclick_button)
        self.tools_box.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gclick_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gclick_button.sizePolicy().hasHeightForWidth())
        self.gclick_button.setSizePolicy(sizePolicy)
        self.gclick_button.setAutoRaise(True)
        self.gclick_button.setObjectName("gclick_button")
        self.horizontalLayout_4.addWidget(self.gclick_button)
        self.cart_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cart_button.sizePolicy().hasHeightForWidth())
        self.cart_button.setSizePolicy(sizePolicy)
        self.cart_button.setAutoRaise(True)
        self.cart_button.setObjectName("cart_button")
        self.horizontalLayout_4.addWidget(self.cart_button)
        self.gclose_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gclose_button.sizePolicy().hasHeightForWidth())
        self.gclose_button.setSizePolicy(sizePolicy)
        self.gclose_button.setAutoRaise(True)
        self.gclose_button.setObjectName("gclose_button")
        self.horizontalLayout_4.addWidget(self.gclose_button)
        self.gopen_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gopen_button.sizePolicy().hasHeightForWidth())
        self.gopen_button.setSizePolicy(sizePolicy)
        self.gopen_button.setAutoRaise(True)
        self.gopen_button.setObjectName("gopen_button")
        self.horizontalLayout_4.addWidget(self.gopen_button)
        self.reset_pressure_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pressure_button.sizePolicy().hasHeightForWidth())
        self.reset_pressure_button.setSizePolicy(sizePolicy)
        self.reset_pressure_button.setAutoRaise(True)
        self.reset_pressure_button.setObjectName("reset_pressure_button")
        self.horizontalLayout_4.addWidget(self.reset_pressure_button)
        self.tools_box.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tools_box)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsSuperView = QtGui.QGraphicsView(self.layoutWidget)
        self.graphicsSuperView.setStyleSheet("QTextEdit { background: palette(base); } \n"
"#main QAbstractScrollArea[style=\"mac\"] { border-color: #8e8e8e #bebebe #bebebe #bebebe; }\n"
"#main QAbstractScrollArea[style=\"cde\"] { border-color: #7c7c8d #9a9ab0 #9a9ab0 #8f8fa4; }\n"
"#main QAbstractScrollArea[style=\"motif\"] { border-color: #a6a6a6 #efefef #efefef #a6a6a6; }\n"
"#main QAbstractScrollArea[style=\"windows\"] { border-color: #8b8b8b transparent transparent #a7a49f; }\n"
"#main QAbstractScrollArea[style=\"plastique\"] { border-color: #8e8e8e #d5d5d5 #d5d5d5 #bebebe; }\n"
"#main QAbstractScrollArea[style=\"cleanlooks\"] { border-color: #a8a099 #dedad6 #dedad6 #c4bcb4; }\n"
"#main QAbstractScrollArea[style=\"windowsvista\"] { border-color: #abadb3 #dbdfe6 #e3e9ef #e2e3ea; }\n"
"#main QAbstractScrollArea:focus[style=\"windowsvista\"] { border-color: #3d7bad #a4c9e3 #b7d9ed #b5cfe7; }\n"
"\n"
"#main #graphicsSuperView { background-color: #f2f2f2; }\n"
"#main #graphicsSuperView[style=\"cde\"] { background-color: #aaaac2; }\n"
"#main #graphicsSuperView[style=\"motif\"] { background-color: #e5e5e5; }\n"
"#main #graphicsSuperView[style=\"windows\"] { background-color: #fafafa; }\n"
"")
        self.graphicsSuperView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsSuperView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsSuperView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphicsSuperView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsSuperView.setOptimizationFlags(QtGui.QGraphicsView.DontAdjustForAntialiasing|QtGui.QGraphicsView.DontClipPainter|QtGui.QGraphicsView.DontSavePainterState)
        self.graphicsSuperView.setObjectName("graphicsSuperView")
        self.verticalLayout_2.addWidget(self.graphicsSuperView)
        self.zoomPanel = QtGui.QWidget(self.layoutWidget)
        self.zoomPanel.setMinimumSize(QtCore.QSize(1, 22))
        self.zoomPanel.setStyleSheet("#main[style=\"cde\"] #zoomPanel, #main[style=\"motif\"] #zoomPanel, #main[style=\"plastique\"] #zoomPanel, #main[style=\"windows\"] #zoomPanel, #main[style=\"cde\"] #zoomWidget, #main[style=\"motif\"] #zoomWidget, #main[style=\"plastique\"] #zoomWidget, #main[style=\"windows\"] #zoomWidget, #main[style=\"gtk\"] #zoomWidget, #main[style=\"gtk\"] #zoomWidget { min-height: 27px; max-height: 27px; }\n"
"#main[style=\"windowsvista\"] #zoomWidget, #main[style=\"windowsvista\"] #zoomWidget { min-height: 26px; max-height: 26px; }")
        self.zoomPanel.setObjectName("zoomPanel")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.zoomPanel)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtGui.QWidget(self.zoomPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(16, 22))
        self.widget_2.setMaximumSize(QtCore.QSize(16, 22))
        self.widget_2.setObjectName("widget_2")
        self.animationSpinner = AnimationSpinner(self.widget_2)
        self.animationSpinner.setGeometry(QtCore.QRect(0, 5, 16, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationSpinner.sizePolicy().hasHeightForWidth())
        self.animationSpinner.setSizePolicy(sizePolicy)
        self.animationSpinner.setMinimumSize(QtCore.QSize(16, 16))
        self.animationSpinner.setMaximumSize(QtCore.QSize(16, 16))
        self.animationSpinner.setText("")
        self.animationSpinner.setPixmap(QtGui.QPixmap(":/animationspinner"))
        self.animationSpinner.setObjectName("animationSpinner")
        self.horizontalLayout_5.addWidget(self.widget_2)
        spacerItem = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.zoomWidget = QtGui.QWidget(self.zoomPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomWidget.sizePolicy().hasHeightForWidth())
        self.zoomWidget.setSizePolicy(sizePolicy)
        self.zoomWidget.setMinimumSize(QtCore.QSize(220, 22))
        self.zoomWidget.setMaximumSize(QtCore.QSize(220, 22))
        self.zoomWidget.setObjectName("zoomWidget")
        self.zoomInButton = QtGui.QToolButton(self.zoomWidget)
        self.zoomInButton.setGeometry(QtCore.QRect(204, 9, 16, 13))
        self.zoomInButton.setStyleSheet("#zoomInButton { image: url(\':/zoombig\'); border: 0; margin: 0; padding: 0; }\n"
"#zoomInButton:pressed { image: url(\':/zoombig_pressed\'); }")
        self.zoomInButton.setObjectName("zoomInButton")
        self.zoomSlider = QtGui.QSlider(self.zoomWidget)
        self.zoomSlider.setGeometry(QtCore.QRect(72, 5, 124, 22))
        self.zoomSlider.setStyleSheet("border: 0;")
        self.zoomSlider.setMinimum(1)
        self.zoomSlider.setMaximum(1000)
        self.zoomSlider.setProperty("value", 100)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setObjectName("zoomSlider")
        self.zoomOutButton = QtGui.QToolButton(self.zoomWidget)
        self.zoomOutButton.setGeometry(QtCore.QRect(51, 11, 10, 9))
        self.zoomOutButton.setStyleSheet("#zoomOutButton { image: url(\':/zoomsmall\'); border: 0; margin: 0; padding: 0; }\n"
"#zoomOutButton:pressed { image: url(\':/zoomsmall_pressed\'); }")
        self.zoomOutButton.setText("")
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.zoomLevel = QtGui.QLabel(self.zoomWidget)
        self.zoomLevel.setGeometry(QtCore.QRect(1, 7, 42, 14))
        self.zoomLevel.setStyleSheet("font-size: 9px;")
        self.zoomLevel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.zoomLevel.setObjectName("zoomLevel")
        self.horizontalLayout_5.addWidget(self.zoomWidget)
        self.verticalLayout_2.addWidget(self.zoomPanel)
        self.properties_box = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.properties_box.sizePolicy().hasHeightForWidth())
        self.properties_box.setSizePolicy(sizePolicy)
        self.properties_box.setFlat(False)
        self.properties_box.setCheckable(False)
        self.properties_box.setObjectName("properties_box")
        self.label = QtGui.QLabel(self.properties_box)
        self.label.setGeometry(QtCore.QRect(17, 25, 62, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.properties_box)
        self.label_2.setGeometry(QtCore.QRect(17, 58, 62, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtGui.QLineEdit(self.properties_box)
        self.lineEdit.setGeometry(QtCore.QRect(85, 25, 146, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.properties_box)
        self.lineEdit_2.setGeometry(QtCore.QRect(85, 58, 146, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget)
        RCommanderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RCommanderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        RCommanderWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RCommanderWindow)
        self.statusbar.setObjectName("statusbar")
        RCommanderWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(RCommanderWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(RCommanderWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtGui.QAction(RCommanderWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen0 = QtGui.QAction(RCommanderWindow)
        self.actionOpen0.setObjectName("actionOpen0")
        self.actionSave0 = QtGui.QAction(RCommanderWindow)
        self.actionSave0.setObjectName("actionSave0")
        self.actionSave_As = QtGui.QAction(RCommanderWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtGui.QAction(RCommanderWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtGui.QAction(RCommanderWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtGui.QAction(RCommanderWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(RCommanderWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy = QtGui.QAction(RCommanderWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste0 = QtGui.QAction(RCommanderWindow)
        self.actionPaste0.setObjectName("actionPaste0")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen0)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave0)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste0)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(RCommanderWindow)
        self.tools_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RCommanderWindow)

    def retranslateUi(self, RCommanderWindow):
        RCommanderWindow.setWindowTitle(QtGui.QApplication.translate("RCommanderWindow", "RCommanderWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tuck_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Tuck", None, QtGui.QApplication.UnicodeUTF8))
        self.navigate_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Navigate", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab), QtGui.QApplication.translate("RCommanderWindow", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.aseg_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Aided Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.oselect_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Object Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.lclick_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Laser Click", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab_2), QtGui.QApplication.translate("RCommanderWindow", "Perception", None, QtGui.QApplication.UnicodeUTF8))
        self.gclick_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Click", None, QtGui.QApplication.UnicodeUTF8))
        self.cart_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Cartesian", None, QtGui.QApplication.UnicodeUTF8))
        self.gclose_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Close", None, QtGui.QApplication.UnicodeUTF8))
        self.gopen_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Open", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_pressure_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Reset Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab_3), QtGui.QApplication.translate("RCommanderWindow", "Manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.animationSpinner.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "The script is running.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Zooms in.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomSlider.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Sets the zoom level.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Zooms out.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLevel.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Zoom to actual size.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLevel.setText(QtGui.QApplication.translate("RCommanderWindow", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.properties_box.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RCommanderWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen0.setText(QtGui.QApplication.translate("RCommanderWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave0.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("RCommanderWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("RCommanderWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("RCommanderWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("RCommanderWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("RCommanderWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste0.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))

from nodebox.gui.qt.widgets.animationspinner import AnimationSpinner
import resources_rc
import resources_rc
