# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCommander.ui'
#
# Created: Thu May 26 16:58:34 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RCommanderWindow(object):
    def setupUi(self, RCommanderWindow):
        RCommanderWindow.setObjectName("RCommanderWindow")
        RCommanderWindow.resize(786, 651)
        self.centralwidget = QtGui.QWidget(RCommanderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools_box = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_box.sizePolicy().hasHeightForWidth())
        self.tools_box.setSizePolicy(sizePolicy)
        self.tools_box.setObjectName("tools_box")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tuck_button = QtGui.QToolButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuck_button.sizePolicy().hasHeightForWidth())
        self.tuck_button.setSizePolicy(sizePolicy)
        self.tuck_button.setAutoRaise(True)
        self.tuck_button.setObjectName("tuck_button")
        self.horizontalLayout_2.addWidget(self.tuck_button)
        self.navigate_button = QtGui.QToolButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigate_button.sizePolicy().hasHeightForWidth())
        self.navigate_button.setSizePolicy(sizePolicy)
        self.navigate_button.setAutoRaise(True)
        self.navigate_button.setObjectName("navigate_button")
        self.horizontalLayout_2.addWidget(self.navigate_button)
        self.tools_box.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aseg_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aseg_button.sizePolicy().hasHeightForWidth())
        self.aseg_button.setSizePolicy(sizePolicy)
        self.aseg_button.setAutoRaise(True)
        self.aseg_button.setObjectName("aseg_button")
        self.horizontalLayout_3.addWidget(self.aseg_button)
        self.oselect_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oselect_button.sizePolicy().hasHeightForWidth())
        self.oselect_button.setSizePolicy(sizePolicy)
        self.oselect_button.setAutoRaise(True)
        self.oselect_button.setObjectName("oselect_button")
        self.horizontalLayout_3.addWidget(self.oselect_button)
        self.lclick_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lclick_button.sizePolicy().hasHeightForWidth())
        self.lclick_button.setSizePolicy(sizePolicy)
        self.lclick_button.setAutoRaise(True)
        self.lclick_button.setObjectName("lclick_button")
        self.horizontalLayout_3.addWidget(self.lclick_button)
        self.tools_box.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gclick_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gclick_button.sizePolicy().hasHeightForWidth())
        self.gclick_button.setSizePolicy(sizePolicy)
        self.gclick_button.setAutoRaise(True)
        self.gclick_button.setObjectName("gclick_button")
        self.horizontalLayout_4.addWidget(self.gclick_button)
        self.cart_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cart_button.sizePolicy().hasHeightForWidth())
        self.cart_button.setSizePolicy(sizePolicy)
        self.cart_button.setAutoRaise(True)
        self.cart_button.setObjectName("cart_button")
        self.horizontalLayout_4.addWidget(self.cart_button)
        self.gclose_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gclose_button.sizePolicy().hasHeightForWidth())
        self.gclose_button.setSizePolicy(sizePolicy)
        self.gclose_button.setAutoRaise(True)
        self.gclose_button.setObjectName("gclose_button")
        self.horizontalLayout_4.addWidget(self.gclose_button)
        self.gopen_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gopen_button.sizePolicy().hasHeightForWidth())
        self.gopen_button.setSizePolicy(sizePolicy)
        self.gopen_button.setAutoRaise(True)
        self.gopen_button.setObjectName("gopen_button")
        self.horizontalLayout_4.addWidget(self.gopen_button)
        self.reset_pressure_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pressure_button.sizePolicy().hasHeightForWidth())
        self.reset_pressure_button.setSizePolicy(sizePolicy)
        self.reset_pressure_button.setAutoRaise(True)
        self.reset_pressure_button.setObjectName("reset_pressure_button")
        self.horizontalLayout_4.addWidget(self.reset_pressure_button)
        self.tools_box.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tools_box)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtGui.QSplitter(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphicsView = QtGui.QGraphicsView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.properties_box = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.properties_box.sizePolicy().hasHeightForWidth())
        self.properties_box.setSizePolicy(sizePolicy)
        self.properties_box.setFlat(False)
        self.properties_box.setCheckable(False)
        self.properties_box.setObjectName("properties_box")
        self.label = QtGui.QLabel(self.properties_box)
        self.label.setGeometry(QtCore.QRect(17, 25, 62, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.properties_box)
        self.label_2.setGeometry(QtCore.QRect(17, 58, 62, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtGui.QLineEdit(self.properties_box)
        self.lineEdit.setGeometry(QtCore.QRect(85, 25, 146, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.properties_box)
        self.lineEdit_2.setGeometry(QtCore.QRect(85, 58, 146, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget)
        RCommanderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RCommanderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        RCommanderWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RCommanderWindow)
        self.statusbar.setObjectName("statusbar")
        RCommanderWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(RCommanderWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(RCommanderWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtGui.QAction(RCommanderWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen0 = QtGui.QAction(RCommanderWindow)
        self.actionOpen0.setObjectName("actionOpen0")
        self.actionSave0 = QtGui.QAction(RCommanderWindow)
        self.actionSave0.setObjectName("actionSave0")
        self.actionSave_As = QtGui.QAction(RCommanderWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtGui.QAction(RCommanderWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtGui.QAction(RCommanderWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtGui.QAction(RCommanderWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(RCommanderWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy = QtGui.QAction(RCommanderWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste0 = QtGui.QAction(RCommanderWindow)
        self.actionPaste0.setObjectName("actionPaste0")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen0)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave0)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste0)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(RCommanderWindow)
        self.tools_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RCommanderWindow)

    def retranslateUi(self, RCommanderWindow):
        RCommanderWindow.setWindowTitle(QtGui.QApplication.translate("RCommanderWindow", "RCommanderWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tuck_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Tuck", None, QtGui.QApplication.UnicodeUTF8))
        self.navigate_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Navigate", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab), QtGui.QApplication.translate("RCommanderWindow", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.aseg_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Aided Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.oselect_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Object Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.lclick_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Laser Click", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab_2), QtGui.QApplication.translate("RCommanderWindow", "Perception", None, QtGui.QApplication.UnicodeUTF8))
        self.gclick_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Click", None, QtGui.QApplication.UnicodeUTF8))
        self.cart_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Cartesian", None, QtGui.QApplication.UnicodeUTF8))
        self.gclose_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Close", None, QtGui.QApplication.UnicodeUTF8))
        self.gopen_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Open", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_pressure_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Reset Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab_3), QtGui.QApplication.translate("RCommanderWindow", "Manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.properties_box.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RCommanderWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen0.setText(QtGui.QApplication.translate("RCommanderWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave0.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("RCommanderWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("RCommanderWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("RCommanderWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("RCommanderWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("RCommanderWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste0.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))

