# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCommander.ui'
#
# Created: Thu Jun  9 12:00:38 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RCommanderWindow(object):
    def setupUi(self, RCommanderWindow):
        RCommanderWindow.setObjectName("RCommanderWindow")
        RCommanderWindow.resize(1046, 875)
        self.centralwidget = QtGui.QWidget(RCommanderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools_box = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_box.sizePolicy().hasHeightForWidth())
        self.tools_box.setSizePolicy(sizePolicy)
        self.tools_box.setObjectName("tools_box")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tools_box.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aseg_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aseg_button.sizePolicy().hasHeightForWidth())
        self.aseg_button.setSizePolicy(sizePolicy)
        self.aseg_button.setAutoRaise(True)
        self.aseg_button.setObjectName("aseg_button")
        self.horizontalLayout_3.addWidget(self.aseg_button)
        self.oselect_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oselect_button.sizePolicy().hasHeightForWidth())
        self.oselect_button.setSizePolicy(sizePolicy)
        self.oselect_button.setAutoRaise(True)
        self.oselect_button.setObjectName("oselect_button")
        self.horizontalLayout_3.addWidget(self.oselect_button)
        self.lclick_button = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lclick_button.sizePolicy().hasHeightForWidth())
        self.lclick_button.setSizePolicy(sizePolicy)
        self.lclick_button.setAutoRaise(True)
        self.lclick_button.setObjectName("lclick_button")
        self.horizontalLayout_3.addWidget(self.lclick_button)
        self.tools_box.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gclick_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gclick_button.sizePolicy().hasHeightForWidth())
        self.gclick_button.setSizePolicy(sizePolicy)
        self.gclick_button.setAutoRaise(True)
        self.gclick_button.setObjectName("gclick_button")
        self.horizontalLayout_4.addWidget(self.gclick_button)
        self.cart_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cart_button.sizePolicy().hasHeightForWidth())
        self.cart_button.setSizePolicy(sizePolicy)
        self.cart_button.setAutoRaise(True)
        self.cart_button.setObjectName("cart_button")
        self.horizontalLayout_4.addWidget(self.cart_button)
        self.gclose_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gclose_button.sizePolicy().hasHeightForWidth())
        self.gclose_button.setSizePolicy(sizePolicy)
        self.gclose_button.setAutoRaise(True)
        self.gclose_button.setObjectName("gclose_button")
        self.horizontalLayout_4.addWidget(self.gclose_button)
        self.gopen_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gopen_button.sizePolicy().hasHeightForWidth())
        self.gopen_button.setSizePolicy(sizePolicy)
        self.gopen_button.setAutoRaise(True)
        self.gopen_button.setObjectName("gopen_button")
        self.horizontalLayout_4.addWidget(self.gopen_button)
        self.reset_pressure_button = QtGui.QToolButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pressure_button.sizePolicy().hasHeightForWidth())
        self.reset_pressure_button.setSizePolicy(sizePolicy)
        self.reset_pressure_button.setAutoRaise(True)
        self.reset_pressure_button.setObjectName("reset_pressure_button")
        self.horizontalLayout_4.addWidget(self.reset_pressure_button)
        self.tools_box.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tools_box)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtGui.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphics_widget = QtGui.QWidget(self.splitter)
        self.graphics_widget.setObjectName("graphics_widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.graphics_widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtGui.QWidget(self.graphics_widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_edge_button = QtGui.QToolButton(self.widget_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../u/hnguyen/svn/wg/rcommander/qt/images/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_edge_button.setIcon(icon)
        self.add_edge_button.setCheckable(True)
        self.add_edge_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.add_edge_button.setAutoRaise(True)
        self.add_edge_button.setArrowType(QtCore.Qt.NoArrow)
        self.add_edge_button.setObjectName("add_edge_button")
        self.horizontalLayout.addWidget(self.add_edge_button)
        self.add_state_button = QtGui.QToolButton(self.widget_3)
        self.add_state_button.setAutoRaise(True)
        self.add_state_button.setObjectName("add_state_button")
        self.horizontalLayout.addWidget(self.add_state_button)
        self.delete_button = QtGui.QToolButton(self.widget_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../u/hnguyen/svn/wg/rcommander/qt/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon1)
        self.delete_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_button.setAutoRaise(True)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.zoom_widget = QtGui.QWidget(self.widget_3)
        self.zoom_widget.setObjectName("zoom_widget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.zoom_widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zoomLevel = QtGui.QLabel(self.zoom_widget)
        self.zoomLevel.setStyleSheet("font-size: 9px;")
        self.zoomLevel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.zoomLevel.setObjectName("zoomLevel")
        self.horizontalLayout_5.addWidget(self.zoomLevel)
        self.zoomOutButton = QtGui.QToolButton(self.zoom_widget)
        self.zoomOutButton.setStyleSheet("#zoomOutButton { image: url(\':/zoomsmall\'); border: 0; margin: 0; padding: 0; }\n"
"#zoomOutButton:pressed { image: url(\':/zoomsmall_pressed\'); }")
        self.zoomOutButton.setText("")
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout_5.addWidget(self.zoomOutButton)
        self.zoomSlider = QtGui.QSlider(self.zoom_widget)
        self.zoomSlider.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSlider.sizePolicy().hasHeightForWidth())
        self.zoomSlider.setSizePolicy(sizePolicy)
        self.zoomSlider.setStyleSheet("border: 0;")
        self.zoomSlider.setMinimum(1)
        self.zoomSlider.setMaximum(1000)
        self.zoomSlider.setProperty("value", 100)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setObjectName("zoomSlider")
        self.horizontalLayout_5.addWidget(self.zoomSlider)
        self.zoomInButton = QtGui.QToolButton(self.zoom_widget)
        self.zoomInButton.setStyleSheet("#zoomInButton { image: url(\':/zoombig\'); border: 0; margin: 0; padding: 0; }\n"
"#zoomInButton:pressed { image: url(\':/zoombig_pressed\'); }")
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout_5.addWidget(self.zoomInButton)
        self.horizontalLayout.addWidget(self.zoom_widget)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.graphicsSuperView = QtGui.QGraphicsView(self.graphics_widget)
        self.graphicsSuperView.setStyleSheet("QTextEdit { background: palette(base); } \n"
"#main QAbstractScrollArea[style=\"mac\"] { border-color: #8e8e8e #bebebe #bebebe #bebebe; }\n"
"#main QAbstractScrollArea[style=\"cde\"] { border-color: #7c7c8d #9a9ab0 #9a9ab0 #8f8fa4; }\n"
"#main QAbstractScrollArea[style=\"motif\"] { border-color: #a6a6a6 #efefef #efefef #a6a6a6; }\n"
"#main QAbstractScrollArea[style=\"windows\"] { border-color: #8b8b8b transparent transparent #a7a49f; }\n"
"#main QAbstractScrollArea[style=\"plastique\"] { border-color: #8e8e8e #d5d5d5 #d5d5d5 #bebebe; }\n"
"#main QAbstractScrollArea[style=\"cleanlooks\"] { border-color: #a8a099 #dedad6 #dedad6 #c4bcb4; }\n"
"#main QAbstractScrollArea[style=\"windowsvista\"] { border-color: #abadb3 #dbdfe6 #e3e9ef #e2e3ea; }\n"
"#main QAbstractScrollArea:focus[style=\"windowsvista\"] { border-color: #3d7bad #a4c9e3 #b7d9ed #b5cfe7; }\n"
"\n"
"#main #graphicsSuperView { background-color: #f2f2f2; }\n"
"#main #graphicsSuperView[style=\"cde\"] { background-color: #aaaac2; }\n"
"#main #graphicsSuperView[style=\"motif\"] { background-color: #e5e5e5; }\n"
"#main #graphicsSuperView[style=\"windows\"] { background-color: #fafafa; }\n"
"")
        self.graphicsSuperView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsSuperView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsSuperView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphicsSuperView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsSuperView.setOptimizationFlags(QtGui.QGraphicsView.DontAdjustForAntialiasing|QtGui.QGraphicsView.DontClipPainter|QtGui.QGraphicsView.DontSavePainterState)
        self.graphicsSuperView.setObjectName("graphicsSuperView")
        self.verticalLayout_2.addWidget(self.graphicsSuperView)
        self.node_edit_area = QtGui.QWidget(self.splitter)
        self.node_edit_area.setObjectName("node_edit_area")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.node_edit_area)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.node_settings_tabs = QtGui.QTabWidget(self.node_edit_area)
        self.node_settings_tabs.setObjectName("node_settings_tabs")
        self.properties_tab = QtGui.QWidget()
        self.properties_tab.setObjectName("properties_tab")
        self.formLayout = QtGui.QFormLayout(self.properties_tab)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.properties_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.properties_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.node_settings_tabs.addTab(self.properties_tab, "")
        self.connections_tab = QtGui.QWidget()
        self.connections_tab.setObjectName("connections_tab")
        self.formLayout_4 = QtGui.QFormLayout(self.connections_tab)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtGui.QLabel(self.connections_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem3)
        self.comboBox = QtGui.QComboBox(self.connections_tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.node_settings_tabs.addTab(self.connections_tab, "")
        self.verticalLayout_3.addWidget(self.node_settings_tabs)
        self.behavior_properties_buttons_box = QtGui.QWidget(self.node_edit_area)
        self.behavior_properties_buttons_box.setObjectName("behavior_properties_buttons_box")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.behavior_properties_buttons_box)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.run_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(50)
        font.setBold(False)
        self.run_button.setFont(font)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_6.addWidget(self.run_button)
        self.save_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(50)
        font.setBold(False)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_6.addWidget(self.save_button)
        self.add_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_6.addWidget(self.add_button)
        self.reset_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_6.addWidget(self.reset_button)
        self.verticalLayout_3.addWidget(self.behavior_properties_buttons_box)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame)
        RCommanderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RCommanderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        RCommanderWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RCommanderWindow)
        self.statusbar.setObjectName("statusbar")
        RCommanderWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(RCommanderWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(RCommanderWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtGui.QAction(RCommanderWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen0 = QtGui.QAction(RCommanderWindow)
        self.actionOpen0.setObjectName("actionOpen0")
        self.actionSave0 = QtGui.QAction(RCommanderWindow)
        self.actionSave0.setObjectName("actionSave0")
        self.actionSave_As = QtGui.QAction(RCommanderWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtGui.QAction(RCommanderWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtGui.QAction(RCommanderWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtGui.QAction(RCommanderWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(RCommanderWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy = QtGui.QAction(RCommanderWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste0 = QtGui.QAction(RCommanderWindow)
        self.actionPaste0.setObjectName("actionPaste0")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen0)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave0)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste0)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(RCommanderWindow)
        self.tools_box.setCurrentIndex(0)
        self.node_settings_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(RCommanderWindow)

    def retranslateUi(self, RCommanderWindow):
        RCommanderWindow.setWindowTitle(QtGui.QApplication.translate("RCommanderWindow", "RCommanderWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab), QtGui.QApplication.translate("RCommanderWindow", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.aseg_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Aided Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.oselect_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Object Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.lclick_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Laser Click", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab_2), QtGui.QApplication.translate("RCommanderWindow", "Perception", None, QtGui.QApplication.UnicodeUTF8))
        self.gclick_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Click", None, QtGui.QApplication.UnicodeUTF8))
        self.cart_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Cartesian", None, QtGui.QApplication.UnicodeUTF8))
        self.gclose_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Close", None, QtGui.QApplication.UnicodeUTF8))
        self.gopen_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Gripper Open", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_pressure_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Reset Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_box.setTabText(self.tools_box.indexOf(self.tab_3), QtGui.QApplication.translate("RCommanderWindow", "Manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.add_edge_button.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Add Edge Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.add_edge_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Add Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.add_state_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Add State", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Delete Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLevel.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Zoom to actual size.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLevel.setText(QtGui.QApplication.translate("RCommanderWindow", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Zooms out.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomSlider.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Sets the zoom level.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Zooms in.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.node_settings_tabs.setTabText(self.node_settings_tabs.indexOf(self.properties_tab), QtGui.QApplication.translate("RCommanderWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("RCommanderWindow", "preempted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("RCommanderWindow", "aborted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("RCommanderWindow", "succeeded", None, QtGui.QApplication.UnicodeUTF8))
        self.node_settings_tabs.setTabText(self.node_settings_tabs.indexOf(self.connections_tab), QtGui.QApplication.translate("RCommanderWindow", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.run_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RCommanderWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen0.setText(QtGui.QApplication.translate("RCommanderWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave0.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("RCommanderWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("RCommanderWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("RCommanderWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("RCommanderWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("RCommanderWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste0.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc
