(cl:defpackage ptp_arm_action-msg
  (:use )
  (:export
   "<LINEARMOVEMENTACTION>"
   "LINEARMOVEMENTACTION"
   "<LINEARMOVEMENTGOAL>"
   "LINEARMOVEMENTGOAL"
   "<LINEARMOVEMENTACTIONGOAL>"
   "LINEARMOVEMENTACTIONGOAL"
   "<LINEARMOVEMENTRESULT>"
   "LINEARMOVEMENTRESULT"
   "<LINEARMOVEMENTACTIONRESULT>"
   "LINEARMOVEMENTACTIONRESULT"
   "<LINEARMOVEMENTFEEDBACK>"
   "LINEARMOVEMENTFEEDBACK"
   "<LINEARMOVEMENTACTIONFEEDBACK>"
   "LINEARMOVEMENTACTIONFEEDBACK"
  ))

