; Auto-generated. Do not edit!


(cl:in-package ptp_arm_action-msg)


;//! \htmlinclude LinearMovementFeedback.msg.html

(cl:defclass <LinearMovementFeedback> (roslisp-msg-protocol:ros-message)
  ((error
    :reader error
    :initarg :error
    :type geometry_msgs-msg:Vector3
    :initform (cl:make-instance 'geometry_msgs-msg:Vector3)))
)

(cl:defclass LinearMovementFeedback (<LinearMovementFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LinearMovementFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LinearMovementFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ptp_arm_action-msg:<LinearMovementFeedback> is deprecated: use ptp_arm_action-msg:LinearMovementFeedback instead.")))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <LinearMovementFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ptp_arm_action-msg:error-val is deprecated.  Use ptp_arm_action-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LinearMovementFeedback>) ostream)
  "Serializes a message object of type '<LinearMovementFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'error) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LinearMovementFeedback>) istream)
  "Deserializes a message object of type '<LinearMovementFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'error) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LinearMovementFeedback>)))
  "Returns string type for a message object of type '<LinearMovementFeedback>"
  "ptp_arm_action/LinearMovementFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LinearMovementFeedback)))
  "Returns string type for a message object of type 'LinearMovementFeedback"
  "ptp_arm_action/LinearMovementFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LinearMovementFeedback>)))
  "Returns md5sum for a message object of type '<LinearMovementFeedback>"
  "ddcdcf876fa71cb72996e49795c08c06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LinearMovementFeedback)))
  "Returns md5sum for a message object of type 'LinearMovementFeedback"
  "ddcdcf876fa71cb72996e49795c08c06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LinearMovementFeedback>)))
  "Returns full string definition for message of type '<LinearMovementFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Vector3 error~%~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LinearMovementFeedback)))
  "Returns full string definition for message of type 'LinearMovementFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Vector3 error~%~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LinearMovementFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'error))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LinearMovementFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LinearMovementFeedback
    (cl:cons ':error (error msg))
))
