; Auto-generated. Do not edit!


(cl:in-package ptp_arm_action-msg)


;//! \htmlinclude LinearMovementResult.msg.html

(cl:defclass <LinearMovementResult> (roslisp-msg-protocol:ros-message)
  ((error
    :reader error
    :initarg :error
    :type geometry_msgs-msg:Vector3
    :initform (cl:make-instance 'geometry_msgs-msg:Vector3)))
)

(cl:defclass LinearMovementResult (<LinearMovementResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LinearMovementResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LinearMovementResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ptp_arm_action-msg:<LinearMovementResult> is deprecated: use ptp_arm_action-msg:LinearMovementResult instead.")))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <LinearMovementResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ptp_arm_action-msg:error-val is deprecated.  Use ptp_arm_action-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LinearMovementResult>) ostream)
  "Serializes a message object of type '<LinearMovementResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'error) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LinearMovementResult>) istream)
  "Deserializes a message object of type '<LinearMovementResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'error) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LinearMovementResult>)))
  "Returns string type for a message object of type '<LinearMovementResult>"
  "ptp_arm_action/LinearMovementResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LinearMovementResult)))
  "Returns string type for a message object of type 'LinearMovementResult"
  "ptp_arm_action/LinearMovementResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LinearMovementResult>)))
  "Returns md5sum for a message object of type '<LinearMovementResult>"
  "ddcdcf876fa71cb72996e49795c08c06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LinearMovementResult)))
  "Returns md5sum for a message object of type 'LinearMovementResult"
  "ddcdcf876fa71cb72996e49795c08c06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LinearMovementResult>)))
  "Returns full string definition for message of type '<LinearMovementResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Vector3 error~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LinearMovementResult)))
  "Returns full string definition for message of type 'LinearMovementResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Vector3 error~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LinearMovementResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'error))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LinearMovementResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LinearMovementResult
    (cl:cons ':error (error msg))
))
