; Auto-generated. Do not edit!


(cl:in-package ptp_arm_action-msg)


;//! \htmlinclude LinearMovementGoal.msg.html

(cl:defclass <LinearMovementGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass LinearMovementGoal (<LinearMovementGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LinearMovementGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LinearMovementGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ptp_arm_action-msg:<LinearMovementGoal> is deprecated: use ptp_arm_action-msg:LinearMovementGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <LinearMovementGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ptp_arm_action-msg:goal-val is deprecated.  Use ptp_arm_action-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LinearMovementGoal>) ostream)
  "Serializes a message object of type '<LinearMovementGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LinearMovementGoal>) istream)
  "Deserializes a message object of type '<LinearMovementGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LinearMovementGoal>)))
  "Returns string type for a message object of type '<LinearMovementGoal>"
  "ptp_arm_action/LinearMovementGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LinearMovementGoal)))
  "Returns string type for a message object of type 'LinearMovementGoal"
  "ptp_arm_action/LinearMovementGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LinearMovementGoal>)))
  "Returns md5sum for a message object of type '<LinearMovementGoal>"
  "85ae384b155cfbcdf597bf321f1d0169")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LinearMovementGoal)))
  "Returns md5sum for a message object of type 'LinearMovementGoal"
  "85ae384b155cfbcdf597bf321f1d0169")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LinearMovementGoal>)))
  "Returns full string definition for message of type '<LinearMovementGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped goal~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LinearMovementGoal)))
  "Returns full string definition for message of type 'LinearMovementGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped goal~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LinearMovementGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LinearMovementGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LinearMovementGoal
    (cl:cons ':goal (goal msg))
))
