/* Auto-generated by genmsg_cpp for file /wg/stor1a/hnguyen/svn/wg/ptp_arm_action/msg/LinearMovementGoal.msg */
#ifndef PTP_ARM_ACTION_MESSAGE_LINEARMOVEMENTGOAL_H
#define PTP_ARM_ACTION_MESSAGE_LINEARMOVEMENTGOAL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "geometry_msgs/PoseStamped.h"

namespace ptp_arm_action
{
template <class ContainerAllocator>
struct LinearMovementGoal_ : public ros::Message
{
  typedef LinearMovementGoal_<ContainerAllocator> Type;

  LinearMovementGoal_()
  : relative(false)
  , trans_vel(0.0)
  , rot_vel(0.0)
  , goal()
  {
  }

  LinearMovementGoal_(const ContainerAllocator& _alloc)
  : relative(false)
  , trans_vel(0.0)
  , rot_vel(0.0)
  , goal(_alloc)
  {
  }

  typedef uint8_t _relative_type;
  uint8_t relative;

  typedef double _trans_vel_type;
  double trans_vel;

  typedef double _rot_vel_type;
  double rot_vel;

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  goal;


private:
  static const char* __s_getDataType_() { return "ptp_arm_action/LinearMovementGoal"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3eceff484681a8278d5e078b51a65c24"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool relative\n\
float64 trans_vel\n\
float64 rot_vel\n\
geometry_msgs/PoseStamped goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, relative);
    ros::serialization::serialize(stream, trans_vel);
    ros::serialization::serialize(stream, rot_vel);
    ros::serialization::serialize(stream, goal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, relative);
    ros::serialization::deserialize(stream, trans_vel);
    ros::serialization::deserialize(stream, rot_vel);
    ros::serialization::deserialize(stream, goal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(relative);
    size += ros::serialization::serializationLength(trans_vel);
    size += ros::serialization::serializationLength(rot_vel);
    size += ros::serialization::serializationLength(goal);
    return size;
  }

  typedef boost::shared_ptr< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct LinearMovementGoal
typedef  ::ptp_arm_action::LinearMovementGoal_<std::allocator<void> > LinearMovementGoal;

typedef boost::shared_ptr< ::ptp_arm_action::LinearMovementGoal> LinearMovementGoalPtr;
typedef boost::shared_ptr< ::ptp_arm_action::LinearMovementGoal const> LinearMovementGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptp_arm_action

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3eceff484681a8278d5e078b51a65c24";
  }

  static const char* value(const  ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3eceff484681a827ULL;
  static const uint64_t static_value2 = 0x8d5e078b51a65c24ULL;
};

template<class ContainerAllocator>
struct DataType< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptp_arm_action/LinearMovementGoal";
  }

  static const char* value(const  ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool relative\n\
float64 trans_vel\n\
float64 rot_vel\n\
geometry_msgs/PoseStamped goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.relative);
    stream.next(m.trans_vel);
    stream.next(m.rot_vel);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LinearMovementGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptp_arm_action::LinearMovementGoal_<ContainerAllocator> & v) 
  {
    s << indent << "relative: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relative);
    s << indent << "trans_vel: ";
    Printer<double>::stream(s, indent + "  ", v.trans_vel);
    s << indent << "rot_vel: ";
    Printer<double>::stream(s, indent + "  ", v.rot_vel);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTP_ARM_ACTION_MESSAGE_LINEARMOVEMENTGOAL_H

