# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCommander.ui'
#
# Created: Tue Oct 25 15:32:48 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RCommanderWindow(object):
    def setupUi(self, RCommanderWindow):
        RCommanderWindow.setObjectName("RCommanderWindow")
        RCommanderWindow.resize(1046, 875)
        self.centralwidget = QtGui.QWidget(RCommanderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools_box = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_box.sizePolicy().hasHeightForWidth())
        self.tools_box.setSizePolicy(sizePolicy)
        self.tools_box.setObjectName("tools_box")
        self.verticalLayout.addWidget(self.tools_box)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtGui.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphics_widget = QtGui.QWidget(self.splitter)
        self.graphics_widget.setObjectName("graphics_widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.graphics_widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtGui.QWidget(self.graphics_widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.start_state_button = QtGui.QToolButton(self.widget_3)
        self.start_state_button.setAutoRaise(True)
        self.start_state_button.setObjectName("start_state_button")
        self.horizontalLayout.addWidget(self.start_state_button)
        self.add_outcome_button = QtGui.QToolButton(self.widget_3)
        self.add_outcome_button.setCheckable(True)
        self.add_outcome_button.setAutoRaise(True)
        self.add_outcome_button.setObjectName("add_outcome_button")
        self.horizontalLayout.addWidget(self.add_outcome_button)
        self.delete_button = QtGui.QToolButton(self.widget_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../u/hnguyen/svn/wg/rcommander/qt/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon)
        self.delete_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_button.setAutoRaise(True)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.add_to_library_button = QtGui.QToolButton(self.widget_3)
        self.add_to_library_button.setAutoRaise(True)
        self.add_to_library_button.setObjectName("add_to_library_button")
        self.horizontalLayout.addWidget(self.add_to_library_button)
        self.library_button = QtGui.QToolButton(self.widget_3)
        self.library_button.setCheckable(True)
        self.library_button.setAutoRaise(True)
        self.library_button.setObjectName("library_button")
        self.horizontalLayout.addWidget(self.library_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.graphicsSuperView = QtGui.QGraphicsView(self.graphics_widget)
        self.graphicsSuperView.setStyleSheet("QTextEdit { background: palette(base); } \n"
"#main QAbstractScrollArea[style=\"mac\"] { border-color: #8e8e8e #bebebe #bebebe #bebebe; }\n"
"#main QAbstractScrollArea[style=\"cde\"] { border-color: #7c7c8d #9a9ab0 #9a9ab0 #8f8fa4; }\n"
"#main QAbstractScrollArea[style=\"motif\"] { border-color: #a6a6a6 #efefef #efefef #a6a6a6; }\n"
"#main QAbstractScrollArea[style=\"windows\"] { border-color: #8b8b8b transparent transparent #a7a49f; }\n"
"#main QAbstractScrollArea[style=\"plastique\"] { border-color: #8e8e8e #d5d5d5 #d5d5d5 #bebebe; }\n"
"#main QAbstractScrollArea[style=\"cleanlooks\"] { border-color: #a8a099 #dedad6 #dedad6 #c4bcb4; }\n"
"#main QAbstractScrollArea[style=\"windowsvista\"] { border-color: #abadb3 #dbdfe6 #e3e9ef #e2e3ea; }\n"
"#main QAbstractScrollArea:focus[style=\"windowsvista\"] { border-color: #3d7bad #a4c9e3 #b7d9ed #b5cfe7; }\n"
"\n"
"#main #graphicsSuperView { background-color: #f2f2f2; }\n"
"#main #graphicsSuperView[style=\"cde\"] { background-color: #aaaac2; }\n"
"#main #graphicsSuperView[style=\"motif\"] { background-color: #e5e5e5; }\n"
"#main #graphicsSuperView[style=\"windows\"] { background-color: #fafafa; }\n"
"")
        self.graphicsSuperView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsSuperView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsSuperView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphicsSuperView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsSuperView.setOptimizationFlags(QtGui.QGraphicsView.DontAdjustForAntialiasing|QtGui.QGraphicsView.DontClipPainter|QtGui.QGraphicsView.DontSavePainterState)
        self.graphicsSuperView.setObjectName("graphicsSuperView")
        self.verticalLayout_2.addWidget(self.graphicsSuperView)
        self.edit_panel = QtGui.QWidget(self.splitter)
        self.edit_panel.setObjectName("edit_panel")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.edit_panel)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.node_settings_tabs = QtGui.QTabWidget(self.edit_panel)
        self.node_settings_tabs.setObjectName("node_settings_tabs")
        self.properties_container = QtGui.QWidget()
        self.properties_container.setObjectName("properties_container")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.properties_container)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.properties_tab = QtGui.QWidget(self.properties_container)
        self.properties_tab.setObjectName("properties_tab")
        self.formLayout = QtGui.QFormLayout(self.properties_tab)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.properties_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.properties_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.label_3 = QtGui.QLabel(self.properties_tab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.widget = QtGui.QWidget(self.properties_tab)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.radioButton_2 = QtGui.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.widget)
        self.verticalLayout_4.addWidget(self.properties_tab)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.node_settings_tabs.addTab(self.properties_container, "")
        self.connections_tab = QtGui.QWidget()
        self.connections_tab.setObjectName("connections_tab")
        self.formLayout_4 = QtGui.QFormLayout(self.connections_tab)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtGui.QLabel(self.connections_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem4)
        self.comboBox = QtGui.QComboBox(self.connections_tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.node_settings_tabs.addTab(self.connections_tab, "")
        self.verticalLayout_3.addWidget(self.node_settings_tabs)
        self.behavior_properties_buttons_box = QtGui.QWidget(self.edit_panel)
        self.behavior_properties_buttons_box.setObjectName("behavior_properties_buttons_box")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.behavior_properties_buttons_box)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.run_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(50)
        font.setBold(False)
        self.run_button.setFont(font)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_6.addWidget(self.run_button)
        self.save_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(50)
        font.setBold(False)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_6.addWidget(self.save_button)
        self.add_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_6.addWidget(self.add_button)
        self.reset_button = QtGui.QPushButton(self.behavior_properties_buttons_box)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_6.addWidget(self.reset_button)
        self.verticalLayout_3.addWidget(self.behavior_properties_buttons_box)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame)
        RCommanderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RCommanderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        RCommanderWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RCommanderWindow)
        self.statusbar.setObjectName("statusbar")
        RCommanderWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(RCommanderWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(RCommanderWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtGui.QAction(RCommanderWindow)
        self.actionNew.setObjectName("actionNew")
        self.action_open = QtGui.QAction(RCommanderWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtGui.QAction(RCommanderWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtGui.QAction(RCommanderWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.actionClose = QtGui.QAction(RCommanderWindow)
        self.actionClose.setObjectName("actionClose")
        self.action_quit = QtGui.QAction(RCommanderWindow)
        self.action_quit.setObjectName("action_quit")
        self.actionCut = QtGui.QAction(RCommanderWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(RCommanderWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy = QtGui.QAction(RCommanderWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste0 = QtGui.QAction(RCommanderWindow)
        self.actionPaste0.setObjectName("actionPaste0")
        self.action_Run = QtGui.QAction(RCommanderWindow)
        self.action_Run.setObjectName("action_Run")
        self.action_stop = QtGui.QAction(RCommanderWindow)
        self.action_stop.setObjectName("action_stop")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_save_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuActions.addAction(self.action_Run)
        self.menuActions.addAction(self.action_stop)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(RCommanderWindow)
        self.tools_box.setCurrentIndex(-1)
        self.node_settings_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RCommanderWindow)

    def retranslateUi(self, RCommanderWindow):
        RCommanderWindow.setWindowTitle(QtGui.QApplication.translate("RCommanderWindow", "RCommanderWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.start_state_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Start State", None, QtGui.QApplication.UnicodeUTF8))
        self.add_outcome_button.setText(QtGui.QApplication.translate("RCommanderWindow", "State Outcome", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setToolTip(QtGui.QApplication.translate("RCommanderWindow", "Delete Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.add_to_library_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Add to Library", None, QtGui.QApplication.UnicodeUTF8))
        self.library_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RCommanderWindow", "HelloText", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("RCommanderWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("RCommanderWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.node_settings_tabs.setTabText(self.node_settings_tabs.indexOf(self.properties_container), QtGui.QApplication.translate("RCommanderWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RCommanderWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("RCommanderWindow", "preempted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("RCommanderWindow", "aborted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("RCommanderWindow", "succeeded", None, QtGui.QApplication.UnicodeUTF8))
        self.node_settings_tabs.setTabText(self.node_settings_tabs.indexOf(self.connections_tab), QtGui.QApplication.translate("RCommanderWindow", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.run_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_button.setText(QtGui.QApplication.translate("RCommanderWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RCommanderWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("RCommanderWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("RCommanderWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("RCommanderWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("RCommanderWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("RCommanderWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("RCommanderWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setText(QtGui.QApplication.translate("RCommanderWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setShortcut(QtGui.QApplication.translate("RCommanderWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save_as.setText(QtGui.QApplication.translate("RCommanderWindow", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("RCommanderWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setText(QtGui.QApplication.translate("RCommanderWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setShortcut(QtGui.QApplication.translate("RCommanderWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("RCommanderWindow", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("RCommanderWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("RCommanderWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste0.setText(QtGui.QApplication.translate("RCommanderWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setText(QtGui.QApplication.translate("RCommanderWindow", "&Run", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setShortcut(QtGui.QApplication.translate("RCommanderWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_stop.setText(QtGui.QApplication.translate("RCommanderWindow", "&Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.action_stop.setShortcut(QtGui.QApplication.translate("RCommanderWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc
